project.name: dunsum

# 보안 속성 모음 import
spring:
  config:
    import: classpath:secretApplication.yml

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

# TODO local, dev(real) 분리
# spring.profiles: local > deprecated 이므로 지양

server.port: 9090

api:
  timeout: 60000

logging:
  level:
    jdbc:
      sqlonly: info
      sqltiming: info
      resultsettable: info
      audit: off
      resultset: off
      connection: off

batch:
  active.host : "127.0.0.1"
  cronData:
    delLog:
      use: true
      cron: "0 0 0 1 */3 *"
      cron-chk: "0 10 0 1 */3 *"
    dnfServer:
      use : true
      cron : "0 0 * * * *"
      cron-chk : "0 5 * * * *"
